# Generated by Django 4.1.3 on 2022-12-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='PROGRAMMER', max_length=100)),
                ('job_type', models.CharField(choices=[('full time', 'full time'), ('part time', 'part time')], default='full time', max_length=100)),
                ('descrption', models.TextField(default='Automatically set the field to now when the object is first created.', max_length=1000, null=True)),
                ('published_at', models.DateField(auto_now=True)),
                ('vanacy', models.IntegerField(default=1)),
                ('salary', models.IntegerField(default=0)),
                ('experiance', models.IntegerField(default=1)),
            ],
        ),
    ]
